apiVersion: v1
kind: ServiceAccount
metadata:
  name: dockerconfig
secrets:
  - name: regcred
---


apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitops
  namespace: default

--- 

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitops-staging
  namespace: staging
subjects:
  - kind: ServiceAccount
    name: gitops
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitops

---  

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitops
rules:
  - apiGroups: [""]
    resources: ["services", "pods", "serviceaccounts", "namespaces"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["*"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["*"]