apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: conferenceclusters.example.crossplane.io
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1alpha1
    kind: ConferenceCluster
  resources:
    - base:
        apiVersion: compute.gcp.crossplane.io/v1beta1
        kind: Network
        spec:
          forProvider:
            autoCreateSubnetworks: false
            routingConfig:
              routingMode: REGIONAL
    - base:
        apiVersion: container.gcp.crossplane.io/v1beta1
        kind: GKECluster
        spec:
          forProvider:
            addonsConfig:
              kubernetesDashboard:
                disabled: true
              networkPolicyConfig:
                disabled: false
            databaseEncryption:
              state: DECRYPTED
            defaultMaxPodsConstraint:
              maxPodsPerNode: 110
            description: Host Cluster instance of basic tier
            ipAllocationPolicy:
              createSubnetwork: true
              useIpAliases: true
            networkPolicy:
              enabled: true
            legacyAbac:
              enabled: false
            podSecurityPolicyConfig:
              enabled: false
            verticalPodAutoscaling:
              enabled: true
            masterAuth:
              username: admin
            loggingService: logging.googleapis.com/kubernetes
            monitoringService: monitoring.googleapis.com/kubernetes
            networkSelector:
              matchControllerRef: true
            location: us-central1
            locations:
              - us-central1-a
              - us-central1-f
          writeConnectionSecretToRef:
            namespace: crossplane-system
      patches:
        - fromFieldPath: "metadata.name"
          toFieldPath: "metadata.annotations[crossplane.io/external-name]"
          transforms:
            - type: string
              string:
                fmt: "hc-%s"
        - fromFieldPath: "metadata.labels"
          toFieldPath: "metadata.labels"
        - fromFieldPath: "metadata.annotations[crossplane.io/external-name]"
          toFieldPath: "metadata.annotations[crossplane.io/external-name]"
        - fromFieldPath: "metadata.uid"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-gkecluster"
        - fromFieldPath: "spec.clusterVersion"
          toFieldPath: "spec.forProvider.initialClusterVersion"
      connectionDetails:
        - fromConnectionSecretKey: kubeconfig
    - base:
        apiVersion: container.gcp.crossplane.io/v1alpha1
        kind: NodePool
        spec:
          forProvider:
            initialNodeCount: 1
            locations:
              - us-central1-a
              - us-central1-f
            autoscaling:
              enabled: true
              minNodeCount: 1
              maxNodeCount: 5
            config:
              diskSizeGb: 100
              diskType: pd-standard
              imageType: COS
              machineType: n2-standard-4
              metadata:
                disable-legacy-endpoints: "true"
              oauthScopes:
                - https://www.googleapis.com/auth/devstorage.read_only
                - https://www.googleapis.com/auth/logging.write
                - https://www.googleapis.com/auth/monitoring
                - https://www.googleapis.com/auth/servicecontrol
                - https://www.googleapis.com/auth/service.management.readonly
                - https://www.googleapis.com/auth/trace.append
                - https://www.googleapis.com/auth/cloud-platform
              preemptible: false
              serviceAccount: default
              shieldedInstanceConfig:
                enableIntegrityMonitoring: true
                enableSecureBoot: true
            clusterSelector:
              matchControllerRef: true
            management:
              autoRepair: true
              autoUpgrade: true
            maxPodsConstraint:
              maxPodsPerNode: 110
      patches:
        - fromFieldPath: "spec.clusterVersion"
          toFieldPath: "spec.forProvider.version"
    # - base:
    #     apiVersion: database.gcp.crossplane.io/v1beta1
    #     kind: CloudSQLInstance
    #     spec:
    #       forProvider:
    #         databaseVersion: MYSQL_5_6
    #         region: us-central1
    #         settings:
    #           tier: db-custom-1-3840
    #           dataDiskType: PD_SSD
    #           ipConfiguration:
    #             ipv4Enabled: true
    #             authorizedNetworks:
    #               - value: "0.0.0.0/0"
    #       writeConnectionSecretToRef:
    #         namespace: crossplane-system
    #   patches:
    #     - fromFieldPath: "metadata.uid"
    #       toFieldPath: "spec.writeConnectionSecretToRef.name"
    #       transforms:
    #         - type: string
    #           string:
    #             fmt: "%s-mysql"
    #     - fromFieldPath: "spec.parameters.storageGB"
    #       toFieldPath: "spec.forProvider.settings.dataDiskSizeGb"
    - base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: ProviderConfig
        spec:
          credentials:
            source: Secret
            secretRef:
              namespace: crossplane-system
              key: kubeconfig
      patches:
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name
        # This ProviderConfig uses the above GKECluster's connection secret as
        # its credentials secret.
        - fromFieldPath: "metadata.uid"
          toFieldPath: spec.credentials.secretRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-gkecluster"
      readinessChecks:
        - type: None
    - base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        metadata:
          annotations: 
            crossplane.io/external-name: conference
        spec:
          forProvider:
            chart:
              name: fmtok8s-app
              repository: https://salaboy.github.io/helm/
              version: 0.1.0
            namespace: conference
            # values:
            #   persistence:
            #     enabled: false
            #   mariadb:
            #     enabled: false
            #   externalDatabase:
            #     create: true
            #     database: wordpress
            #     port: 3306
            # set: 
            #   - name: externalDatabase.host
            #     valueFrom: 
            #       secretKeyRef: 
            #         name: 
            #         namespace: crossplane-system
            #         key: endpoint
            #   - name: externalDatabase.user
            #     valueFrom: 
            #       secretKeyRef: 
            #         name: 
            #         namespace: crossplane-system
            #         key: username
            #   - name: externalDatabase.password
            #     valueFrom: 
            #       secretKeyRef: 
            #         name: 
            #         namespace: crossplane-system
            #         key: password
      # patches:
      #   - fromFieldPath: metadata.name
      #     toFieldPath: spec.providerConfigRef.name
      #   - fromFieldPath: "metadata.uid"
      #     toFieldPath: spec.forProvider.set[0].valueFrom.secretKeyRef.name
      #     transforms:
      #       - type: string
      #         string:
      #           fmt: "%s-mysql"
      #   - fromFieldPath: "metadata.uid"
      #     toFieldPath: spec.forProvider.set[1].valueFrom.secretKeyRef.name
      #     transforms:
      #       - type: string
      #         string:
      #           fmt: "%s-mysql"
      #   - fromFieldPath: "metadata.uid"
      #     toFieldPath: spec.forProvider.set[2].valueFrom.secretKeyRef.name
      #     transforms:
      #       - type: string
      #         string:
      #           fmt: "%s-mysql"

            